exports.fetchZones = (req, res) => {
    const zones = [
      { name: 'Todo CDMX y Área Metropolitana', value: 'estado-8' },
      { name: 'Centro', value: 'zona-15' },
      { name: 'Nor-oriente', value: 'zona-16' },
      { name: 'Norte', value: 'zona-17' },
      { name: 'Oriente', value: 'zona-18' },
      { name: 'Poniente', value: 'zona-19' },
      { name: 'Sur', value: 'zona-20' },
      { name: 'Todo Monterrey y Área Metropolitana', value: 'estado-16' },
      { name: 'Apodaca', value: 'zona-42' },
      { name: 'Escobedo', value: 'zona-43' },
      { name: 'Guadalupe', value: 'zona-44' },
      { name: 'Juárez', value: 'zona-45' },
      { name: 'Monterrey', value: 'zona-46' },
      { name: 'Salinas Victoria', value: 'zona-104' },
      { name: 'San Nicolás', value: 'zona-47' },
      { name: 'San Pedro', value: 'zona-48' },
      { name: 'Santa Catarina', value: 'zona-49' },
      { name: 'Todo Jalisco', value: 'estado-14' },
      { name: 'Cd. Guzmán', value: 'zona-34' },
      { name: 'Guadalajara', value: 'zona-35' },
      { name: 'Ocotlán', value: 'zona-36' },
      { name: 'Puerto Vallarta', value: 'zona-37' },
      { name: 'Tonalá', value: 'zona-38' },
      { name: 'Aguascalientes', value: 'zona-1' },
      { name: 'Todo Baja California', value: 'estado-2' },
      { name: 'Mexicali', value: 'zona-2' },
      { name: 'Tijuana', value: 'zona-3' },
      { name: 'Todo Baja California Sur', value: 'estado-3' },
      { name: 'Cabo San Lucas', value: 'zona-4' },
      { name: 'San Jose Del Cabo', value: 'zona-103' },
      { name: 'Cd. Del Carmen', value: 'zona-6' },
      { name: 'Todo Chiapas', value: 'estado-32' },
      { name: 'Tapachula', value: 'zona-94' },
      { name: 'Tuxtla', value: 'zona-92' },
      { name: 'Todo Chihuahua', value: 'estado-5' },
      { name: 'Cd. Juárez', value: 'zona-7' },
      { name: 'Chihuahua', value: 'zona-8' },
      { name: 'Delicias', value: 'zona-9' },
      { name: 'Todo Coahuila', value: 'estado-6' },
      { name: 'Monclova', value: 'zona-11' },
      { name: 'Piedras Negras', value: 'zona-99' },
      { name: 'Ramos Arizpe', value: 'zona-102' },
      { name: 'Saltillo', value: 'zona-12' },
      { name: 'Torreón', value: 'zona-13' },
      { name: 'Colima', value: 'zona-14' },
      { name: 'Todo Durango', value: 'estado-9' },
      { name: 'Durango', value: 'zona-21' },
      { name: 'El Salto', value: 'zona-118' },
      { name: 'Gómez Palacio', value: 'zona-22' },
      { name: 'Todo Estado De México', value: 'estado-10' },
      { name: 'Atlacomulco', value: 'zona-23' },
      { name: 'Lerma', value: 'zona-24' },
      { name: 'Metepec', value: 'zona-25' },
      { name: 'Toluca', value: 'zona-26' },
      { name: 'Todo Guanajuato', value: 'estado-11' },
      { name: 'Guanajuato', value: 'zona-27' },
      { name: 'Irapuato', value: 'zona-28' },
      { name: 'León', value: 'zona-29' },
      { name: 'Salamanca', value: 'zona-96' },
      { name: 'San Miguel De Allende', value: 'zona-30' },
      { name: 'Zihuatanejo', value: 'zona-106' },
      { name: 'Todo Hidalgo', value: 'estado-13' },
      { name: 'Cd. Sahagún', value: 'zona-116' },
      { name: 'Pachuca', value: 'zona-32' },
      { name: 'Progreso de Obregón', value: 'zona-114' },
      { name: 'Tizayuca', value: 'zona-117' },
      { name: 'Tulancingo', value: 'zona-33' },
      { name: 'Todo Michoacán', value: 'estado-15' },
      { name: 'La Piedad', value: 'zona-95' },
      { name: 'Lázaro Cárdenas', value: 'zona-39' },
      { name: 'Morelia', value: 'zona-40' },
      { name: 'Zamora', value: 'zona-41' },
      { name: 'Todo Morelos', value: 'estado-17' },
      { name: 'Cuautla', value: 'zona-50' },
      { name: 'Cuernavaca', value: 'zona-51' },
      { name: 'Tepic', value: 'zona-52' },
      { name: 'Todo Oaxaca', value: 'estado-20' },
      { name: 'Oaxaca', value: 'zona-54' },
      { name: 'Salina Cruz', value: 'zona-90' },
      { name: 'Tuxtepec', value: 'zona-55' },
      { name: 'Puebla', value: 'zona-56' },
      { name: 'Todo Querétaro', value: 'estado-22' },
      { name: 'Querétaro', value: 'zona-57' },
      { name: 'San Juan Del Rio', value: 'zona-97' },
      { name: 'Todo Quintana Roo', value: 'estado-23' },
      { name: 'Cancún', value: 'zona-58' },
      { name: 'Chetumal', value: 'zona-59' },
      { name: 'Cozumel', value: 'zona-109' },
      { name: 'Playa Del Carmen', value: 'zona-60' },
      { name: 'Todo San Luis Potosí', value: 'estado-24' },
      { name: 'Cd. Valles', value: 'zona-61' },
      { name: 'San Luis Potosí', value: 'zona-62' },
      { name: 'Todo Sinaloa', value: 'estado-25' },
      { name: 'Culiacán', value: 'zona-63' },
      { name: 'Los Mochis', value: 'zona-66' },
      { name: 'Mazatlán', value: 'zona-67' },
      { name: 'Todo Sonora', value: 'estado-26' },
      { name: 'Cananea', value: 'zona-111' },
      { name: 'Guaymas', value: 'zona-69' },
      { name: 'Hermosillo', value: 'zona-70' },
      { name: 'Nacozari De GarcÍa', value: 'zona-71' },
      { name: 'Navojoa', value: 'zona-72' },
      { name: 'Todo Tabasco', value: 'estado-27' },
      { name: 'Cárdenas', value: 'zona-73' },
      { name: 'Villahermosa', value: 'zona-74' },
      { name: 'Todo Tamaulipas', value: 'estado-28' },
      { name: 'Cd. Mante', value: 'zona-75' },
      { name: 'Matamoros', value: 'zona-77' },
      { name: 'Nuevo Laredo', value: 'zona-78' },
      { name: 'Reynosa', value: 'zona-79' },
      { name: 'Río Bravo', value: 'zona-80' },
      { name: 'Tampico', value: 'zona-81' },
      { name: 'Tlaxcala', value: 'zona-105' },
      { name: 'Todo Veracruz', value: 'estado-29' },
      { name: 'Boca del Río', value: 'zona-82' },
      { name: 'Coatzacoalcos', value: 'zona-83' },
      { name: 'Córdoba', value: 'zona-91' },
      { name: 'Poza Rica', value: 'zona-84' },
      { name: 'Veracruz', value: 'zona-85' },
      { name: 'Todo Yucatán', value: 'estado-30' },
      { name: 'Mérida', value: 'zona-86' },
      { name: 'Tizimin', value: 'zona-110' },
      { name: 'Valladolid', value: 'zona-87' },
      { name: 'Todo Zacatecas', value: 'estado-31' },
      { name: 'Fresnillo', value: 'zona-88' },
      { name: 'Rio Grande', value: 'zona-115' },
      { name: 'Zacatecas', value: 'zona-89' }
    ];
  
    res.json(zones);
  };